### PR TITLE
Added OfferFull for reading Price-History from amazon-ECS

### PR DESCRIPTION
**Pull request by mrandibilbao**
Hi, 

i hardcoded OfferFull into search and lookup. Please make the ResponsiveGroups more dynamic, so that we can set the ResponsiveGroups in our application.

thx

### CODE REVIEW

**Comment by joedawson** [comment]
Thanks for your efforts - this PR seems to contain a lot of files I don't want included and one typo (that I've seen). But I'd be happy to add `OfferAll` in the next release.

**Comment by mrandibilbao** [comment]
thanks

**Comment by joedawson** [comment]
No problem, thanks for raising this.

I'll be looking to add an option to the `amazon.php` config file that will allow you to specify what you'd like included in the response group as an array.

So there will be a new option named something like "response_groups" then you can just add or remove anything from the array in the config.

``` php
/**
 * amazon.php
 */
'response_groups' => [
    'Images',
    'ItemAttributes',
    'OfferFull'
]
```

I'll likely add this at some point this weekend.

**Comment by mrandibilbao** [comment]
Hi Joe,
I already coded a function yesterday for adding ResponseGroups.
If you want, i can make a PR in the evening.

Best wishes

Joe Dawson notifications@github.com schrieb am Mi., 17. Feb. 2016 13:24:

**Pull request closed without merging**
